### PR TITLE
Scss sl

### PR DESCRIPTION
**Pull request by SammyLug**

### CODE REVIEW

**Comment by drv0228** [comment]
Hi Sam, I tried to run your branch and encountered the following error:

> ERROR in ./src/components/SubmissionForm/SubmissionDrawer.jsx 6:0-51
> Module not found: Error: Can't resolve '@chakra-ui/icons' in '/Users/dayana/Desktop/P4_Member_Achievement/src/components/SubmissionForm'

It seems like you are missing the @chakra-ui/icons dependency. Could you please add it and push the update? Thank you!

**Review by drv0228 — CHANGES_REQUESTED** [review]
Hi Sam, I tried to run your branch and encountered the following error:

ERROR in ./src/components/SubmissionForm/SubmissionDrawer.jsx 6:0-51
Module not found: Error: Can't resolve '@chakra-ui/icons' in '/Users/dayana/Desktop/P4_Member_Achievement/src/components/SubmissionForm'

It seems like you are missing the @chakra-ui/icons dependency. Could you please add it and push the update? Thank you!

**Comment by SammyLug** [comment]
> Hi Sam, I tried to run your branch and encountered the following error:
> 
> > ERROR in ./src/components/SubmissionForm/SubmissionDrawer.jsx 6:0-51
> > Module not found: Error: Can't resolve '@chakra-ui/icons' in '/Users/dayana/Desktop/P4_Member_Achievement/src/components/SubmissionForm'
> 
> It seems like you are missing the @chakra-ui/icons dependency. Could you please add it and push the update? Thank you!

Hi Dayana, I think you need to npm i then pull to get the import for chakra-ui/icons

**Comment by SammyLug** [comment]
Should be working now!

**Review by drv0228 — APPROVED** [review]
This looks great! Nice job, Sam!

**Pull request merged**
